LOGGING:
    VERSION: "v1"
    RUN_NAME: SimMIM3D_PT_ADNI
    JOBS_DIR: /dhc/home/tim.riedel/bachelor-thesis/jobs
DATA:
    DATA_DIR: /dhc/home/tim.riedel/bachelor-thesis/data/ADNI
    IMG_SIZE: 128
    BATCH_SIZE: 16
    NUM_WORKERS: 16
    MASK_RATIO: 0.7
TRAINING:
    BASE_LR: 3e-4
    WEIGHT_DECAY: 0.0
    WARMUP_EPOCHS: 0
    EPOCHS: 400
    CROSS_VALIDATIONS: 1
MODEL:
    IN_CHANNELS: 1
    PATCH_SIZE: 16
    ENCODER_DROPOUT: 0.1
SYSTEM:
    ACCELERATOR: gpu
    STRATEGY: ddp
    DEVICES: -1
    NODES: 1
