LOGGING:
    VERSION: "1.2.0"
    RUN_NAME: UNETR_FT_Brats
    JOBS_DIR: /dhc/home/tim.riedel/bachelor-thesis/jobs
DATA:
    BRATS_DATA_DIR: /dhc/home/tim.riedel/bachelor-thesis/data/BraTS2017
    IMG_SIZE: 128
    NUM_CLASSES: 3
    BATCH_SIZE: 16
    NUM_WORKERS: 16
TRAINING:
    BASE_LR: 4e-4
    WEIGHT_DECAY: 0.0
    WARMUP_EPOCHS: 0
    EPOCHS: 400
    CROSS_VALIDATIONS: 1
MODEL:
    IN_CHANNELS: 4
    PATCH_SIZE: 16
    ENCODER_CKPT_PATH: '/dhc/home/tim.riedel/bachelor-thesis/jobs/checkpoints/SimMIM3D_PT_Brats_v2.2.5/epoch=379-step=9500.ckpt' 
SYSTEM:
    ACCELERATOR: gpu
    STRATEGY: ddp
    DEVICES: -1
    NODES: 1
    PRECISION: 16-mixed
