LOGGING:
    VERSION: "1.0.0"
    RUN_NAME: UNETR_FT_Brats
    JOBS_DIR: /dhc/home/tim.riedel/bachelor-thesis/jobs
DATA:
    BRATS_DATA_DIR: /dhc/home/tim.riedel/bachelor-thesis/data/BraTS2017
    IMG_SIZE: 128
    NUM_CLASSES: 3
    BATCH_SIZE: 16
    NUM_WORKERS: 16
TRAINING:
    BASE_LR: 3e-4
    WEIGHT_DECAY: 0.005
    WARMUP_EPOCHS: 50
    EPOCHS: 400
    CROSS_VALIDATIONS: 1
MODEL:
    IN_CHANNELS: 4
    PATCH_SIZE: 16
    ENCODER_DROPOUT: 0.1
SYSTEM:
    ACCELERATOR: gpu
    STRATEGY: ddp
    DEVICES: -1
    NODES: 1
    PRECISION: 16-mixed
