LOGGING:
    PROJECT_NAME: brats-finetune
    RUN_NAME: Brats
    JOBS_DIR: /dhc/home/tim.riedel/bachelor-thesis/jobs
    CKPT_DIR: /dhc/home/tim.riedel/bachelor-thesis/jobs/checkpoints
DATA:
    DATA_DIR: /dhc/home/tim.riedel/bachelor-thesis/data/BraTS2017
    IMG_SIZE: 128
    NUM_CLASSES: 4 # including background
    BATCH_SIZE: 8
    NUM_WORKERS: 18
    TRAIN_FRAC: 1.0
TRAINING:
    BASE_LR: 5e-4
    WEIGHT_DECAY: 0.005
    FREEZE_WARMUP_EPOCHS: 20
    LR_WARMUP_EPOCHS: 50
    EPOCHS: 350
    CV_FOLDS: 1
MODEL:
    IN_CHANNELS: 4
    PATCH_SIZE: 16
    ENCODER_DROPOUT: 0.1
SYSTEM:
    ACCELERATOR: gpu
    STRATEGY: ddp_find_unused_parameters_true
    DEVICES: -1
    NODES: 1
