LOGGING:
    RUN_NAME: SimMIM3D_PT_Brats_v2
    WANDB_DIR: /dhc/home/tim.riedel/bachelor-thesis/jobs/wandb
    CHECKPOINT_DIR: /dhc/home/tim.riedel/bachelor-thesis/jobs/checkpoints/SimMIM3D_PT_Brats_v2
DATA:
    BRATS_DATA_DIR: /dhc/home/tim.riedel/bachelor-thesis/data/BraTS2017
    IMG_SIZE: 96
    BATCH_SIZE: 8
    NUM_WORKERS: 16
    MASK_RATIO: 0.75
TRAINING:
    BASE_LR: 3e-4
    WEIGHT_DECAY: 0.005
    WARMUP_EPOCHS: 100
    EPOCHS: 900
MODEL:
    IN_CHANNELS: 4
    PATCH_SIZE: 16
    ENCODER_DROPOUT: 0.1
SYSTEM:
    ACCELERATOR: gpu
    STRATEGY: ddp
    DEVICES: -1
    NODES: 1
    PRECISION: 16-mixed
